### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ghost** [ManneredBoor/frontend-project-template#2]
Hi sir,
This seems like a very very cool project!
I was wondering if you are planning to keep working on it?
And if maybe you would be open to some suggestions, requests for features, etc...
Thanks!

**Comment by bobunderforest** [comment]
Hello! I'm glad you like my project. I'm working on it in my free time. In near future I will implement bower components assembling and finish browserify task.
If you have any suggestions or requests, I am happy to consider them.

**Comment by ghost** [comment]
Hi there,

I more than like it, I totally love it.
I’m working on a whole project workflow and I will be borrowing a lot from you :-)

Maybe we can discuss some things through email, so I don’t pollute your gitlab?

/cheers
jurgen@codebakery.co

**Comment by bobunderforest** [comment]
I wrote to you on email.
