### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by dmitriyK1** [ManneredBoor/frontend-project-template#3]
Please consider following:
- add jeet grid system for stylus
  https://github.com/mojotech/jeet 
  http://jeet.gs/
- add stylus sourcemaps for easier debugging
-  remove #title id from head.jade
- add :before for .clearfix ( to prevent collapsing vertical margins ):
  content: " ";
  display: table;
- https://www.npmjs.com/package/gulp-newer
-   html, body
      font-size 100%        // to allow em-based fonts @media resizing
      -webkit-text-size-adjust 100%        // to prevent size adjust on ios devices
- stylus mixins:

pseudo(value= ' ')
    position: absolute
    display: block
    content value

o(color= red)
    outline 1px solid color

 https://github.com/nDmitry/stylus/blob/master/lib/mixins/fallback.styl
https://github.com/nDmitry/stylus/blob/master/lib/mixins/underline.styl
https://github.com/nDmitry/stylus/blob/master/lib/mixins/rem.styl
https://github.com/nDmitry/stylus/blob/master/lib/mixins/opacity.styl

**Comment by bobunderforest** [comment]
Done
